version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  node:
    docker:
      - image: cimg/node:16.9
  with-chrome:
    docker:
      - image: "cypress/browsers:node14.17.0-chrome88-ff89"
    resource_class: xlarge
workflows:
  build:
    jobs:
      - cypress/run:
          browser: chrome
          executor: with-chrome
          command: npm test
          env: "CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY,APPLITOOLS_API_KEY=$APPLITOOLS_API_KEY,APPLITOOLS_BATCH_ID=$CIRCLE_SHA1"


