# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1

executors:
  node:
    docker:
      - image: cimg/node:16.9
  with-chrome:
    docker:
      - image: "cypress/browsers:node14.17.0-chrome88-ff89"
    resource_class: xlarge

jobs:
  prepareApplitools:
    executor: node
    steps:
      - run:
          name: Prepare Applitools for code push
          command: |
            curl -X POST "https://eyesapi.applitools.com/api/externals/github/push?apiKey=$APPLITOOLS_API_KEY&CommitSha=$CIRCLE_SHA1&BranchName=$CIRCLE_BRANCH" --data "" -L

  runTestPlaceholder:
    executor: node
    steps:
      - run:
        name: run tests placeholder
        command: |
          npm test

  alertApplitools:
    executor: node
    steps:
      - run:
          name: Alert Applitools of completion
          command: |
            curl -X POST "https://eyesapi.applitools.com/api/externals/github/servers/github.com/commit/$CIRCLE_SHA1/complete?apiKey=$APPLITOOLS_API_KEY" -H "Content-Type: application/json" --data '{"serverId": "github.com", "commitSha": "$CIRCLE_SHA1"}' -v -L

workflows:
  sample:
    jobs:
      - cypress/install:
          context: nlo_context
          name: "install"
          executor: with-chrome
          build: "npm install"
      - prepareApplitools:
          context: nlo_context
          requires:
            - install
      - runTestPlaceholder:
          context: nlo_context
          requires:
            - install      
      - alertApplitools:
          context: nlo_context
          requires:
            - cypress