version: 2.1
orbs:
  # use latest 1.x.y version of the orb
  # best practice is to use an exact version
  cypress: cypress-io/cypress@1.16.1
  node: circleci/node@1.1

executors:
  chrome80-ff72:
    docker:
      - image: 'cypress/browsers:node13.6.0-chrome80-ff72'

jobs:
  unit:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - run: sudo apt install libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm test

workflows:
  dependencies:
    jobs:
      - cypress/run:
          name: test dependencies
          filters:
            branches:
              only: /renovate.*/
          no-workspace: true
          record: true
          tags: dependencies,renovate
      - unit